title: LTH's Blog
author: Lê Trung Hoàng
description: >
  Blog của Lê Trung Hoàng.
baseurl: "/blog"
url: "https://lthoang.github.io"
social:
  github: lthoang
  twitter: trhoanglee
  linkedin: lthoang
  facebook: trhoanglee

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

permalink: /:title
google_analytics: UA-70844403-1
related_sites:
  Home: //lthoang.github.io
  Site map: /blog/sitemap.xml
