title: Lê Trung Hoàng
email: trhoanglee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog của Lê Trung Hoàng.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://lthoang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: trhoanglee
github_username:  lthoang

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title
google_analytics: UA-70844403-1